apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdknfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdknfe
  template:
    metadata:
      labels:
        app: sdknfe
    spec:
      containers:
      - image: okteto.dev/sdknfe:latest
        name: sdknfe
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "37d16f15-f837-4fb7-8b1f-9422a19d8519"
        - name: Vless_Path
          value: "/vlwf555"
        - name: Vmess_UUID
          value: "37d16f15-f837-4fb7-8b1f-9422a19d8519"
        - name: Vmess_Path
          value: "/vmfw666"
        - name: Share_Path
          value: "/v2link"
